### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by p4l1ly** [lorisdanto/symbolicautomata#26] opened 2019-08-13 10:21 UTC
Hello, I am compiling your project with `mvn clean install`

```
Maven home: /opt/maven
Java version: 1.8.0_222, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.1.4-arch1-1-arch", arch: "amd64", family: "unix"
```

and some unit tests fail on the following two assertions. What am I missing?

## 1) The intersection of SRA:

https://github.com/lorisdanto/symbolicautomata/blob/f4d34085b0f43d223b4d22ff74ae95598b6ccaed/TestSVPA/src/test/SRA/SRAUnitTest.java#L65

These are the three automata in the test
**intersection**
```
Automaton: 1 transitions, 2 states
Transitions
S: 0 -[a-z]/{[]},{[0, 1]},{[0, 1]}-> 1
Initial State
0
Final States
1
```

**autA**
```
Automaton: 2 transitions, 1 states
Transitions
S: 0 -[a-z]/0*-> 0
S: 0 -[a-z]/0=-> 0
Initial State
0
Final States
0
```

**autB**
```
Automaton: 4 transitions, 2 states
Transitions
S: 0 -[a-z]/0*-> 1
S: 0 -[a-z]/0=-> 1
S: 1 -[0-9]/0=-> 1
S: 1 -[0-9]/0*-> 1
Initial State
0
Final States
1
```

Time to time, the **intersection** automaton looks differently and the test then passes, e.g.:
```
Automaton: 1 transitions, 2 states
Transitions
S: 0 -[a-z]/{[0]},{[0]},{[0]}-> 1
Initial State
0
Final States
1
```

Further debugging is beyond the scope of my familiarity with the code. I don't even understand why there is `assertFalse` on the linked line of code (should not the intersection automaton accept the word 'a'?)

## 2) testGetOutputSFA

https://github.com/lorisdanto/symbolicautomata/blob/f4d34085b0f43d223b4d22ff74ae95598b6ccaed/TestSVPA/src/test/SFT/SFTUnitTest.java#L1400

**expected1**
```
Automaton: 1 transitions, 1 states
Transitions
S: 0 -[\u0000-\uffff]-> 0
Initial State
0
Final States
```

**noOutputFunctions.getOutputSFA(ba)**
```
Automaton: 1 transitions, 2 states
Transitions
E: 0 --> 1
Initial State
0
Final States
1
```

**Comment by shxuy** [comment] 2019-08-13 13:32
Hi! I am the author of SFTUnitTest.java and SFT.java as a former student of professor D'Antoni. It seems that I misunderstood the meaning of the output language of a transducer when I wrote these code and D'Antoni debugged it last December without telling me. In other words, SFT.java works well but the comparing SFA named 'expected1' which is constructed by hand is wrong.
Perhaps I would update the unit test of SFT or just delete the test case you mentioned, depending on professor's decision.

**Comment by lorisdanto** [comment] 2019-08-13 16:21
Thanks for catching the issue. I fixed the testGetOutputSFA bug.

I can't reproduce the SRA bug on my machine, but I was getting the same error on my home machine. I'll investigate further.

**Comment by tiferrei** [comment] 2019-08-14 09:53
Hi I am one of the SRA authors. That specific test has always passed on my machine, although I have noticed certain cases where it would fail on CI. I was never able to reproduce it. I will also give it a look.

**Comment by lorisdanto** [comment] 2019-08-14 15:19
@p4l1ly Thanks a ton for your bug report!

We have now fixed both bugs! I'm closing the issue
Thanks @matteo-sammartino for fixing the SRA bug.

**Closed by lorisdanto** 2019-08-14 15:19 UTC
