### ISSUE TITLE
Test are not working

### ISSUE THREAD

**Issue by Gillani0** [lorisdanto/symbolicautomata#1] opened 2015-09-07 16:08 UTC
Hi,
 I tried to use the test for SVPA but seems like couple of files are missing in "theory" package. Thanks

Regards
Gillani

**Comment by lorisdanto** [comment] 2015-09-07 16:38
Hi Gilliani,

I guess you tried using Eclipse to open to project and you get that some files are missing.
If I think you have the problem I have in mind, you need to update to a recent version of Eclipse (I'm using Mars). The problem is that some older version have a builtin JVM 1.7 that gets confused when compiling with Java 1.8.

If this is not the problem you get, please let me know and I'll try to figure out what's going on.

-Loris

**Comment by lorisdanto** [comment] 2015-09-07 17:22
Hi Gillani,

I also mavenized the project. You should now be able to build it straight from command line. Check the new readme file for instructions.

Thank you for your report. Let me know if things work so I can close the Issue.

Best,
-Loris

**Closed** 2018-03-08 16:17 UTC
